---
apiVersion: platform.example.com/v1alpha1
kind: XStorageBucket
metadata:
  name: example
status:
  conditions:
  - lastTransitionTime: "2024-01-01T00:00:00Z"
    message: 'Unready resources: example-acl, example-boc, example-bucket, and 3 more'
    reason: Creating
    status: "False"
    type: Ready
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketACL
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-acl
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-acl
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    acl: public-read
    bucketRef:
      name: example-bucket
    region: us-west-1
  managementPolicies:
  - '*'
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-boc
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-boc
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    bucketRef:
      name: example-bucket
    region: us-west-1
    rule:
    - objectOwnership: BucketOwnerPreferred
  managementPolicies:
  - '*'
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-bucket
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-bucket
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-1
  managementPolicies:
  - '*'
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketServerSideEncryptionConfiguration
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-encryption
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-encryption
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    bucketRef:
      name: example-bucket
    region: us-west-1
    rule:
    - applyServerSideEncryptionByDefault:
      - sseAlgorithm: AES256
      bucketKeyEnabled: true
  managementPolicies:
  - '*'
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPublicAccessBlock
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-pab
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-pab
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    blockPublicAcls: false
    blockPublicPolicy: false
    bucketRef:
      name: example-bucket
    ignorePublicAcls: false
    region: us-west-1
    restrictPublicBuckets: false
  managementPolicies:
  - '*'
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketVersioning
metadata:
  annotations:
    crossplane.io/composition-resource-name: example-versioning
  generateName: example-
  labels:
    crossplane.io/composite: example
  name: example-versioning
  ownerReferences:
  - apiVersion: platform.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XStorageBucket
    name: example
    uid: ""
spec:
  deletionPolicy: Delete
  forProvider:
    bucketRef:
      name: example-bucket
    region: us-west-1
    versioningConfiguration:
    - status: Enabled
  managementPolicies:
  - '*'
